### PR TITLE
No parenthesis on `eq` or `eql` in specs

### PR DESCRIPTION
**Pull request by jcarouth**
From discussion here https://github.com/liftopia/rtopia/pull/1195#discussion_r31071167
and in liftopia/rtopia#1319 I decided to encode this in our styleguide for all future
reference and questions.

RFC @maglfmn @jakefolio @cwd-liftopia

### CODE REVIEW

**Comment by jcarouth** [comment]
So everyone thinks this is awesome then?

**Comment by jakefolio** [comment]
Awesome? I'll agree to do it. Success/Pain will be assessed over time. i.e.
not being able to do hash literals as the eql value

==============================================
Jake Smith
Sr. Platform Engineer | Liftopia
jsmith@liftopia.com  |  M: 214.724.0620

**Comment by cwd-liftopia** [comment]
I'm with @jakefolio on this being potentially annoying over time. I think it's great to have no parens on a single value, but for something like `expect(my_thing).to eq my_old_thing + 1` or any kind of complex value I think using the parens is much easier to read.

**Comment by jcarouth** [comment]
Okay, so then we have changed our minds and we simply don't care about usage of parens for `eq` or `eql` in specs? That has been my position all along but people keep bringing it up.

**Comment by maglfmn** [comment]
Ugh. Yeah the complex values is kind of tricky... And I hate to make the case where "if comparing against a complex value, parens. Otherwise, none." But! I suppose that's the case in other places too (like for omitting parentheses for a method call).

**Comment by jcarouth** [comment]
Alright. So at least we have this PR to reference going forward.

**Pull request closed without merging**
